package com.smartscan.ai.ui.strings

import com.smartscan.ai.domain.model.AppLanguage

data class StringResources(
    val appName: String,
    val searchHint: String,
    val syncNow: String,
    val syncing: String,
    val grantPermission: String,
    val permissionRequired: String,
    val paywallMessage: String,
    val buyPremium: String,
    val noTextRecognized: String,
    val settings: String,
    val language: String,
    val back: String,
    val syncingGallery: String,
    val syncComplete: String,
    val freeLimitReached: String,
    val imageDetails: String,
    val share: String,
    val delete: String,
    val confirmDelete: String,
    val deleteMessage: String,
    val cancel: String,
    val extractedText: String,
    val tags: String,
    val metadata: String,
    val status: String,
    val scannedAt: String,
    val uri: String,
    val imagePreview: String,
    val trialUsage: String,
    val trialRemaining: String,
    val upgradeCta: String,
    val premiumLabel: String,
    val unlimitedLabel: String,
    val screenshotsFolderEmpty: String,
    val paywallTitle: String,
    val paywallSubtitle: String,
    val paywallFeatureUnlimited: String,
    val paywallFeatureNoWatermarks: String,
    val paywallFeatureFaster: String,
    val paywallFeatureCloud: String,
    val paywallMonthlyTitle: String,
    val paywallMonthlySubtitle: String,
    val paywallLifetimeTitle: String,
    val paywallLifetimeSubtitle: String,
    val paywallChooseLifetime: String,
    val paywallTryMonthly: String,
    val paywallTerms: String,
    val paywallPrivacy: String,
    val paywallRestore: String,
    val paywallPriceNote: String,
    val paywallMonthlyPeriod: String,
    val paywallLifetimePeriod: String,
    val paywallMonthlyFeatureA: String,
    val paywallMonthlyFeatureB: String,
    val paywallLifetimeFeatureA: String,
    val paywallLifetimeFeatureB: String,
    val showEmptyScans: String,
    val hideEmptyScans: String,
    val photoCreatedAt: String,
    val syncScreenshotsOnlyTitle: String,
    val syncScreenshotsOnlySubtitle: String,
    val clearAllScans: String,
    val clearAllScansTitle: String,
    val clearAllScansMessage: String,
    val clearAllScansSuccess: String
)

fun getStrings(language: AppLanguage): StringResources = when (language) {
    AppLanguage.ENGLISH -> englishStrings
    AppLanguage.RUSSIAN -> russianStrings
    AppLanguage.SPANISH -> spanishStrings
    AppLanguage.GERMAN -> germanStrings
    AppLanguage.CHINESE -> chineseStrings
}

private val englishStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Search text and tags",
    syncNow = "Sync now",
    syncing = "Syncing...",
    grantPermission = "Grant",
    permissionRequired = "Allow media access to scan gallery screenshots",
    paywallMessage = "Free limit reached. Upgrade to Premium to continue scanning.",
    buyPremium = "Get Premium",
    noTextRecognized = "No text recognized",
    settings = "Settings",
    language = "Language",
    back = "Back",
    syncingGallery = "Syncing gallery...",
    syncComplete = "Synced %d, skipped %d.",
    freeLimitReached = "Synced %d, skipped %d. Free limit reached.",
    imageDetails = "Image Details",
    share = "Share",
    delete = "Delete",
    confirmDelete = "Delete Image?",
    deleteMessage = "This image will be permanently deleted from the database.",
    cancel = "Cancel",
    extractedText = "Extracted Text",
    tags = "Tags",
    metadata = "Metadata",
    status = "Status",
    scannedAt = "Scanned at",
    uri = "URI",
    imagePreview = "Image preview",
    trialUsage = "Trial: %d/%d scans used",
    trialRemaining = "%d scans remaining",
    upgradeCta = "Upgrade",
    premiumLabel = "Premium",
    unlimitedLabel = "Unlimited",
    screenshotsFolderEmpty = "Your Screenshots folder is empty.",
    paywallTitle = "Upgrade to Premium",
    paywallSubtitle = "Unlock unlimited scanning and powerful features to search all your photos",
    paywallFeatureUnlimited = "Unlimited scans",
    paywallFeatureNoWatermarks = "Export results (TXT/PDF)",
    paywallFeatureFaster = "Batch processing",
    paywallFeatureCloud = "Priority support",
    paywallMonthlyTitle = "Monthly",
    paywallMonthlySubtitle = "Best for trying premium",
    paywallLifetimeTitle = "Lifetime (Best Value!)",
    paywallLifetimeSubtitle = "Save more, pay once forever",
    paywallChooseLifetime = "Choose Lifetime",
    paywallTryMonthly = "Try Monthly",
    paywallTerms = "Terms",
    paywallPrivacy = "Privacy",
    paywallRestore = "Restore",
    paywallPriceNote = "Prices may vary by country",
    paywallMonthlyPeriod = "/ month",
    paywallLifetimePeriod = "one-time",
    paywallMonthlyFeatureA = "Cancel anytime",
    paywallMonthlyFeatureB = "Auto-renews",
    paywallLifetimeFeatureA = "Unlimited updates",
    paywallLifetimeFeatureB = "Never pay again",
    showEmptyScans = "Show empty",
    hideEmptyScans = "Hide empty",
    photoCreatedAt = "Photo created at",
    syncScreenshotsOnlyTitle = "Sync screenshots only",
    syncScreenshotsOnlySubtitle = "When enabled, sync prioritizes only images from screenshot folders",
    clearAllScans = "Clear all",
    clearAllScansTitle = "Clear all scans?",
    clearAllScansMessage = "This will permanently delete all scanned records from the app database.",
    clearAllScansSuccess = "All scanned records were removed."
)

private val russianStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Поиск текста и тегов",
    syncNow = "Синхронизировать",
    syncing = "Синхронизация...",
    grantPermission = "Разрешить",
    permissionRequired = "Разрешите доступ к медиафайлам для сканирования галереи",
    paywallMessage = "Достигнут лимит бесплатной версии. Перейдите на Premium для продолжения.",
    buyPremium = "Перейти на Premium",
    noTextRecognized = "Текст не распознан",
    settings = "Настройки",
    language = "Язык",
    back = "Назад",
    syncingGallery = "Синхронизация галереи...",
    syncComplete = "Синхронизировано %d, пропущено %d.",
    freeLimitReached = "Синхронизировано %d, пропущено %d. Достигнут лимит.",
    imageDetails = "Детали изображения",
    share = "Поделиться",
    delete = "Удалить",
    confirmDelete = "Удалить изображение?",
    deleteMessage = "Это изображение будет безвозвратно удалено из базы данных.",
    cancel = "Отмена",
    extractedText = "Распознанный текст",
    tags = "Теги",
    metadata = "Метаданные",
    status = "Статус",
    scannedAt = "Отсканировано",
    uri = "URI",
    imagePreview = "Превью изображения",
    trialUsage = "Пробный период: %d/%d сканов использовано",
    trialRemaining = "Осталось %d сканов",
    upgradeCta = "Обновить",
    premiumLabel = "Premium",
    unlimitedLabel = "Безлимит",
    screenshotsFolderEmpty = "Папка скриншотов у вас пуста.",
    paywallTitle = "Перейти на Premium",
    paywallSubtitle = "Разблокируйте безлимитное сканирование и мощные функции для поиска по всем фото",
    paywallFeatureUnlimited = "Безлимитные сканы",
    paywallFeatureNoWatermarks = "Экспорт результатов (TXT/PDF)",
    paywallFeatureFaster = "Пакетная обработка",
    paywallFeatureCloud = "Приоритетная поддержка",
    paywallMonthlyTitle = "Месячный",
    paywallMonthlySubtitle = "Лучше для знакомства с Premium",
    paywallLifetimeTitle = "Пожизненный (Лучшая цена!)",
    paywallLifetimeSubtitle = "Сэкономьте больше, заплатите один раз",
    paywallChooseLifetime = "Выбрать пожизненный",
    paywallTryMonthly = "Попробовать месячный",
    paywallTerms = "Условия",
    paywallPrivacy = "Конфиденциальность",
    paywallRestore = "Восстановить",
    paywallPriceNote = "Цены могут отличаться в зависимости от страны",
    paywallMonthlyPeriod = "/ месяц",
    paywallLifetimePeriod = "разовая оплата",
    paywallMonthlyFeatureA = "Отмена в любой момент",
    paywallMonthlyFeatureB = "Автопродление",
    paywallLifetimeFeatureA = "Бессрочные обновления",
    paywallLifetimeFeatureB = "Больше не нужно платить",
    showEmptyScans = "Показать пустые",
    hideEmptyScans = "Скрыть пустые",
    photoCreatedAt = "Фото создано",
    syncScreenshotsOnlyTitle = "Синхронизировать только скриншоты",
    syncScreenshotsOnlySubtitle = "Когда включено, синхронизируются только изображения из папок скриншотов",
    clearAllScans = "Очистить все",
    clearAllScansTitle = "Очистить все сканы?",
    clearAllScansMessage = "Все отсканированные записи будут безвозвратно удалены из базы приложения.",
    clearAllScansSuccess = "Все отсканированные записи удалены."
)

private val spanishStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Buscar texto y etiquetas",
    syncNow = "Sincronizar ahora",
    syncing = "Sincronizando...",
    grantPermission = "Conceder",
    permissionRequired = "Permite el acceso a los medios para escanear capturas de galería",
    paywallMessage = "Se alcanzo el limite gratuito. Actualiza a Premium para continuar escaneando.",
    buyPremium = "Obtener Premium",
    noTextRecognized = "No se reconoció texto",
    settings = "Configuración",
    language = "Idioma",
    back = "Atrás",
    syncingGallery = "Sincronizando galería...",
    syncComplete = "Sincronizado %d, omitido %d.",
    freeLimitReached = "Sincronizado %d, omitido %d. Límite alcanzado.",
    imageDetails = "Detalles de imagen",
    share = "Compartir",
    delete = "Eliminar",
    confirmDelete = "¿Eliminar imagen?",
    deleteMessage = "Esta imagen se eliminará permanentemente de la base de datos.",
    cancel = "Cancelar",
    extractedText = "Texto extraído",
    tags = "Etiquetas",
    metadata = "Metadatos",
    status = "Estado",
    scannedAt = "Escaneado en",
    uri = "URI",
    imagePreview = "Vista previa",
    trialUsage = "Prueba: %d/%d escaneos usados",
    trialRemaining = "%d escaneos restantes",
    upgradeCta = "Mejorar",
    premiumLabel = "Premium",
    unlimitedLabel = "Ilimitado",
    screenshotsFolderEmpty = "Tu carpeta de capturas de pantalla esta vacia.",
    paywallTitle = "Mejorar a Premium",
    paywallSubtitle = "Desbloquea escaneo ilimitado y funciones potentes para buscar en todas tus fotos",
    paywallFeatureUnlimited = "Escaneos ilimitados",
    paywallFeatureNoWatermarks = "Exportar resultados (TXT/PDF)",
    paywallFeatureFaster = "Procesamiento por lotes",
    paywallFeatureCloud = "Soporte prioritario",
    paywallMonthlyTitle = "Mensual",
    paywallMonthlySubtitle = "Ideal para probar premium",
    paywallLifetimeTitle = "De por vida (¡Mejor valor!)",
    paywallLifetimeSubtitle = "Ahorra más, paga una vez para siempre",
    paywallChooseLifetime = "Elegir de por vida",
    paywallTryMonthly = "Probar mensual",
    paywallTerms = "Términos",
    paywallPrivacy = "Privacidad",
    paywallRestore = "Restaurar",
    paywallPriceNote = "Los precios pueden variar según el país",
    paywallMonthlyPeriod = "/ mes",
    paywallLifetimePeriod = "pago único",
    paywallMonthlyFeatureA = "Cancela cuando quieras",
    paywallMonthlyFeatureB = "Renovación automática",
    paywallLifetimeFeatureA = "Actualizaciones ilimitadas",
    paywallLifetimeFeatureB = "Nunca pagues de nuevo",
    showEmptyScans = "Mostrar vacíos",
    hideEmptyScans = "Ocultar vacíos",
    photoCreatedAt = "Foto creada el",
    syncScreenshotsOnlyTitle = "Sincronizar solo capturas",
    syncScreenshotsOnlySubtitle = "Cuando está activado, solo se sincronizan imágenes de carpetas de capturas",
    clearAllScans = "Borrar todo",
    clearAllScansTitle = "Borrar todos los escaneos?",
    clearAllScansMessage = "Esto eliminara permanentemente todos los registros escaneados de la base de datos.",
    clearAllScansSuccess = "Todos los registros escaneados fueron eliminados."
)

private val germanStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Text und Tags suchen",
    syncNow = "Jetzt synchronisieren",
    syncing = "Synchronisiere...",
    grantPermission = "Gewähren",
    permissionRequired = "Erlaube Medienzugriff zum Scannen von Galerie-Screenshots",
    paywallMessage = "Kostenloses Limit erreicht. Upgrade auf Premium, um weiterzuscannen.",
    buyPremium = "Premium holen",
    noTextRecognized = "Kein Text erkannt",
    settings = "Einstellungen",
    language = "Sprache",
    back = "Zurück",
    syncingGallery = "Galerie wird synchronisiert...",
    syncComplete = "Synchronisiert %d, übersprungen %d.",
    freeLimitReached = "Synchronisiert %d, übersprungen %d. Limit erreicht.",
    imageDetails = "Bilddetails",
    share = "Teilen",
    delete = "Löschen",
    confirmDelete = "Bild löschen?",
    deleteMessage = "Dieses Bild wird dauerhaft aus der Datenbank gelöscht.",
    cancel = "Abbrechen",
    extractedText = "Extrahierter Text",
    tags = "Tags",
    metadata = "Metadaten",
    status = "Status",
    scannedAt = "Gescannt am",
    uri = "URI",
    imagePreview = "Bildvorschau",
    trialUsage = "Testphase: %d/%d Scans genutzt",
    trialRemaining = "%d Scans verbleibend",
    upgradeCta = "Upgrade",
    premiumLabel = "Premium",
    unlimitedLabel = "Unbegrenzt",
    screenshotsFolderEmpty = "Dein Screenshot-Ordner ist leer.",
    paywallTitle = "Auf Premium upgraden",
    paywallSubtitle = "Schalte unbegrenztes Scannen und leistungsstarke Funktionen für alle deine Fotos frei",
    paywallFeatureUnlimited = "Unbegrenzte Scans",
    paywallFeatureNoWatermarks = "Ergebnisse exportieren (TXT/PDF)",
    paywallFeatureFaster = "Stapelverarbeitung",
    paywallFeatureCloud = "Prioritäts-Support",
    paywallMonthlyTitle = "Monatlich",
    paywallMonthlySubtitle = "Ideal zum Ausprobieren von Premium",
    paywallLifetimeTitle = "Lebenslang (Bestes Angebot!)",
    paywallLifetimeSubtitle = "Mehr sparen, einmal zahlen",
    paywallChooseLifetime = "Lebenslang wählen",
    paywallTryMonthly = "Monatlich testen",
    paywallTerms = "AGB",
    paywallPrivacy = "Datenschutz",
    paywallRestore = "Wiederherstellen",
    paywallPriceNote = "Preise können je nach Land variieren",
    paywallMonthlyPeriod = "/ Monat",
    paywallLifetimePeriod = "einmalig",
    paywallMonthlyFeatureA = "Jederzeit kündbar",
    paywallMonthlyFeatureB = "Automatische Verlängerung",
    paywallLifetimeFeatureA = "Unbegrenzte Updates",
    paywallLifetimeFeatureB = "Nie wieder zahlen",
    showEmptyScans = "Leere anzeigen",
    hideEmptyScans = "Leere ausblenden",
    photoCreatedAt = "Foto erstellt am",
    syncScreenshotsOnlyTitle = "Nur Screenshots synchronisieren",
    syncScreenshotsOnlySubtitle = "Wenn aktiviert, werden nur Bilder aus Screenshot-Ordnern synchronisiert",
    clearAllScans = "Alles loschen",
    clearAllScansTitle = "Alle Scans loschen?",
    clearAllScansMessage = "Dadurch werden alle gescannten Eintrage dauerhaft aus der App-Datenbank entfernt.",
    clearAllScansSuccess = "Alle gescannten Eintrage wurden entfernt."
)

private val chineseStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "搜索文本和标签",
    syncNow = "立即同步",
    syncing = "同步中...",
    grantPermission = "授权",
    permissionRequired = "允许访问媒体以扫描图库截图",
    paywallMessage = "已达到免费限制。升级到 Premium 以继续扫描。",
    buyPremium = "获取 Premium",
    noTextRecognized = "未识别到文本",
    settings = "设置",
    language = "语言",
    back = "返回",
    syncingGallery = "正在同步图库...",
    syncComplete = "已同步 %d，已跳过 %d。",
    freeLimitReached = "已同步 %d，已跳过 %d。已达到免费限制。",
    imageDetails = "图片详情",
    share = "分享",
    delete = "删除",
    confirmDelete = "删除图片？",
    deleteMessage = "该图片将从本地数据库中永久删除。",
    cancel = "取消",
    extractedText = "识别文本",
    tags = "标签",
    metadata = "元数据",
    status = "状态",
    scannedAt = "扫描时间",
    uri = "URI",
    imagePreview = "图片预览",
    trialUsage = "试用期：已使用 %d/%d 次扫描",
    trialRemaining = "剩余 %d 次扫描",
    upgradeCta = "升级",
    premiumLabel = "Premium",
    unlimitedLabel = "无限",
    screenshotsFolderEmpty = "你的截图文件夹是空的。",
    paywallTitle = "升级到 Premium",
    paywallSubtitle = "解锁无限扫描和强大功能，搜索所有照片",
    paywallFeatureUnlimited = "无限扫描",
    paywallFeatureNoWatermarks = "导出结果 (TXT/PDF)",
    paywallFeatureFaster = "批量处理",
    paywallFeatureCloud = "优先支持",
    paywallMonthlyTitle = "月付",
    paywallMonthlySubtitle = "适合先体验 Premium",
    paywallLifetimeTitle = "终身版（最佳价值！）",
    paywallLifetimeSubtitle = "一次付费，永久使用",
    paywallChooseLifetime = "选择终身版",
    paywallTryMonthly = "试用月付",
    paywallTerms = "条款",
    paywallPrivacy = "隐私",
    paywallRestore = "恢复购买",
    paywallPriceNote = "价格可能因地区而异",
    paywallMonthlyPeriod = "/ 月",
    paywallLifetimePeriod = "一次性",
    paywallMonthlyFeatureA = "可随时取消",
    paywallMonthlyFeatureB = "自动续订",
    paywallLifetimeFeatureA = "无限更新",
    paywallLifetimeFeatureB = "无需再次付费",
    showEmptyScans = "显示空白",
    hideEmptyScans = "隐藏空白",
    photoCreatedAt = "照片创建时间",
    syncScreenshotsOnlyTitle = "仅同步截图",
    syncScreenshotsOnlySubtitle = "开启后，仅同步截图文件夹中的图片",
    clearAllScans = "清空全部",
    clearAllScansTitle = "清空所有扫描记录？",
    clearAllScansMessage = "这将从应用数据库中永久删除所有扫描记录。",
    clearAllScansSuccess = "所有扫描记录已删除。"
)
