package com.smartscan.ai.ui.strings

import com.smartscan.ai.domain.model.AppLanguage

data class StringResources(
    val appName: String,
    val searchHint: String,
    val syncNow: String,
    val syncing: String,
    val grantPermission: String,
    val permissionRequired: String,
    val paywallMessage: String,
    val buyPremium: String,
    val noTextRecognized: String,
    val settings: String,
    val language: String,
    val back: String,
    val syncingGallery: String,
    val syncComplete: String,
    val freeLimitReached: String,
    val syncedLabel: String,
    val skippedLabel: String,
    val imageDetails: String,
    val share: String,
    val delete: String,
    val confirmDelete: String,
    val deleteMessage: String,
    val cancel: String,
    val extractedText: String,
    val tags: String,
    val metadata: String,
    val status: String,
    val scannedAt: String,
    val uri: String,
    val imagePreview: String,
    val trialUsage: String,
    val trialRemaining: String,
    val upgradeCta: String,
    val premiumLabel: String,
    val unlimitedLabel: String,
    val screenshotsFolderEmpty: String,
    val paywallTitle: String,
    val paywallSubtitle: String,
    val paywallFeatureUnlimited: String,
    val paywallFeatureNoWatermarks: String,
    val paywallFeatureFaster: String,
    val paywallFeatureCloud: String,
    val paywallMonthlyTitle: String,
    val paywallMonthlySubtitle: String,
    val paywallLifetimeTitle: String,
    val paywallLifetimeSubtitle: String,
    val paywallChooseLifetime: String,
    val paywallTryMonthly: String,
    val paywallTerms: String,
    val paywallPrivacy: String,
    val paywallRestore: String,
    val paywallPriceNote: String,
    val paywallMonthlyPeriod: String,
    val paywallLifetimePeriod: String,
    val paywallMonthlyFeatureA: String,
    val paywallMonthlyFeatureB: String,
    val paywallLifetimeFeatureA: String,
    val paywallLifetimeFeatureB: String,
    val showEmptyScans: String,
    val hideEmptyScans: String,
    val photoCreatedAt: String,
    val syncScreenshotsOnlyTitle: String,
    val syncScreenshotsOnlySubtitle: String,
    val clearAllScans: String,
    val clearAllScansTitle: String,
    val clearAllScansMessage: String,
    val clearAllScansSuccess: String,
    // === Onboarding ===
    val onboardingTitle1: String,
    val onboardingSubtitle1: String,
    val onboardingTitle2: String,
    val onboardingSubtitle2: String,
    val skip: String,
    val next: String,
    val done: String,
    // === Scanning Progress ===
    val onboardingScanning: String,
    val scannedDocuments: String,
    val scanningHint: String,
    // === Empty State ===
    val emptyStateTitle: String,
    val emptyStateSubtitle: String,
    val emptyStateTip1: String,
    val emptyStateTip2: String,
    val emptyStateTip3: String,
    val scanFirstDocument: String,
    // === Screenshots Folder Empty ===
    val screenshotsFolderEmptyHint: String,
    val currentlyScreenshotsOnly: String,
    val currentlyAllGallery: String,
    val switchToAllGallery: String,
    val syncAllGallery: String,
    // === Sync Control ===
    val stopSync: String,
    val continueSync: String,
    val startOver: String,
    val startOverConfirmTitle: String,
    val startOverConfirmMessage: String,
    val startOverConfirm: String,
    val sortMenu: String,
    val sortBySyncDate: String,
    val sortByPhotoDate: String,
    val russianScanSpeedNotice: String,
    // === Sync Metrics ===
    val syncMetricsScanned: String,
    val syncMetricsElapsedTime: String,
    val syncMetricsLastSync: String,
    val syncMetricsSummaryTitle: String,
    val syncMetricsNow: String,
    val syncMetricsMinutesAgo: String,
    val syncMetricsHoursAgo: String,
    val syncMetricsDaysAgo: String
)

fun getStrings(language: AppLanguage): StringResources = when (language) {
    AppLanguage.ENGLISH -> englishStrings
    AppLanguage.RUSSIAN -> russianStrings
    AppLanguage.SPANISH -> spanishStrings
    AppLanguage.GERMAN -> germanStrings
    AppLanguage.CHINESE -> chineseStrings
}

private val englishStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Search text and tags",
    syncNow = "Sync now",
    syncing = "Syncing...",
    grantPermission = "Grant",
    permissionRequired = "Allow media access to scan gallery screenshots",
    paywallMessage = "Free limit reached. Upgrade to Premium for unlimited scans and no ads.",
    buyPremium = "Get Premium",
    noTextRecognized = "No text recognized",
    settings = "Settings",
    language = "Language",
    back = "Back",
    syncingGallery = "Syncing gallery...",
    syncComplete = "%s %d, %s %d.",
    freeLimitReached = "%s %d, %s %d. Free limit reached.",
    syncedLabel = "Synced",
    skippedLabel = "skipped",
    imageDetails = "Image Details",
    share = "Share",
    delete = "Delete",
    confirmDelete = "Delete Image?",
    deleteMessage = "This image will be permanently deleted from the database.",
    cancel = "Cancel",
    extractedText = "Extracted Text",
    tags = "Tags",
    metadata = "Metadata",
    status = "Status",
    scannedAt = "Scanned at",
    uri = "URI",
    imagePreview = "Image preview",
    trialUsage = "Trial: %d/%d scans used",
    trialRemaining = "%d scans remaining",
    upgradeCta = "Upgrade",
    premiumLabel = "Premium",
    unlimitedLabel = "Unlimited",
    screenshotsFolderEmpty = "Your Screenshots folder is empty.",
    paywallTitle = "Upgrade to Premium",
    paywallSubtitle = "Unlock unlimited scanning and remove ads in Premium",
    paywallFeatureUnlimited = "Unlimited scans",
    paywallFeatureNoWatermarks = "No ads (Premium)",
    paywallFeatureFaster = "Batch processing",
    paywallFeatureCloud = "Priority support",
    paywallMonthlyTitle = "Monthly",
    paywallMonthlySubtitle = "Best for trying premium",
    paywallLifetimeTitle = "Lifetime (Best Value!)",
    paywallLifetimeSubtitle = "Save more, pay once forever",
    paywallChooseLifetime = "Choose Lifetime",
    paywallTryMonthly = "Try Monthly",
    paywallTerms = "Terms",
    paywallPrivacy = "Privacy",
    paywallRestore = "Restore",
    paywallPriceNote = "Prices may vary by country",
    paywallMonthlyPeriod = "/ month",
    paywallLifetimePeriod = "one-time",
    paywallMonthlyFeatureA = "Cancel anytime",
    paywallMonthlyFeatureB = "Auto-renews",
    paywallLifetimeFeatureA = "Unlimited updates",
    paywallLifetimeFeatureB = "Never pay again",
    showEmptyScans = "Show empty",
    hideEmptyScans = "Hide empty",
    photoCreatedAt = "Photo created at",
    syncScreenshotsOnlyTitle = "Sync screenshots only",
    syncScreenshotsOnlySubtitle = "When enabled, sync prioritizes only images from screenshot folders",
    clearAllScans = "Clear all",
    clearAllScansTitle = "Clear all scans?",
    clearAllScansMessage = "This will permanently delete all scanned records from the app database.",
    clearAllScansSuccess = "All scanned records were removed.",
    // === Onboarding ===
    onboardingTitle1 = "We're scanning your gallery",
    onboardingSubtitle1 = "Your Screenshots folder is loading now...",
    onboardingTitle2 = "AI sorts everything for you",
    onboardingSubtitle2 = "Receipts, passports, contracts — automatically organized into folders",
    skip = "Skip",
    next = "Next",
    done = "Done",
    // === Scanning Progress ===
    onboardingScanning = "Scanning your gallery...",
    scannedDocuments = "Processed: %d documents",
    scanningHint = "This may take a moment...",
    // === Empty State ===
    emptyStateTitle = "No documents yet?",
    emptyStateSubtitle = "AI automatically sorts your photos and documents",
    emptyStateTip1 = "Scan receipts, passports, contracts",
    emptyStateTip2 = "AI automatically detects the type",
    emptyStateTip3 = "Everything sorted into folders",
    scanFirstDocument = "Scan first document",
    // === Screenshots Folder Empty ===
    screenshotsFolderEmptyHint = "By default, we sync only the Screenshots folder. You can switch to sync all photos from your gallery.",
    currentlyScreenshotsOnly = "Currently: Screenshots only",
    currentlyAllGallery = "Currently: All gallery",
    switchToAllGallery = "Switch to All Gallery & Sync",
    syncAllGallery = "Sync All Gallery",
    // === Sync Control ===
    stopSync = "Stop",
    continueSync = "Continue",
    startOver = "Start over",
    startOverConfirmTitle = "Start over?",
    startOverConfirmMessage = "This will delete all documents scanned in this session and restart from the beginning.",
    startOverConfirm = "Start over",
    sortMenu = "Sort",
    sortBySyncDate = "Sort by sync date",
    sortByPhotoDate = "Sort by photo date",
    russianScanSpeedNotice = "Russian scanning is currently slower. This will be improved in the next update.",
    // === Sync Metrics ===
    syncMetricsScanned = "Scanned: %d",
    syncMetricsElapsedTime = "Elapsed time: %s",
    syncMetricsLastSync = "Last sync: %s",
    syncMetricsSummaryTitle = "Sync summary",
    syncMetricsNow = "now",
    syncMetricsMinutesAgo = "%dm ago",
    syncMetricsHoursAgo = "%dh ago",
    syncMetricsDaysAgo = "%dd ago"
)

private val russianStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Поиск текста и тегов",
    syncNow = "Синхронизировать",
    syncing = "Синхронизация...",
    grantPermission = "Разрешить",
    permissionRequired = "Разрешите доступ к медиафайлам для сканирования галереи",
    paywallMessage = "Достигнут лимит бесплатной версии. Перейдите на Premium: безлимит и без рекламы.",
    buyPremium = "Перейти на Premium",
    noTextRecognized = "Текст не распознан",
    settings = "Настройки",
    language = "Язык",
    back = "Назад",
    syncingGallery = "Синхронизация галереи...",
    syncComplete = "%s %d, %s %d.",
    freeLimitReached = "%s %d, %s %d. Достигнут лимит.",
    syncedLabel = "Синхронизировано",
    skippedLabel = "Пропущено",
    imageDetails = "Детали изображения",
    share = "Поделиться",
    delete = "Удалить",
    confirmDelete = "Удалить изображение?",
    deleteMessage = "Это изображение будет безвозвратно удалено из базы данных.",
    cancel = "Отмена",
    extractedText = "Распознанный текст",
    tags = "Теги",
    metadata = "Метаданные",
    status = "Статус",
    scannedAt = "Отсканировано",
    uri = "URI",
    imagePreview = "Превью изображения",
    trialUsage = "Пробный период: %d/%d сканов использовано",
    trialRemaining = "Осталось %d сканов",
    upgradeCta = "Обновить",
    premiumLabel = "Premium",
    unlimitedLabel = "Безлимит",
    screenshotsFolderEmpty = "Папка скриншотов у вас пуста.",
    paywallTitle = "Перейти на Premium",
    paywallSubtitle = "Разблокируйте безлимитное сканирование и отключите рекламу в Premium",
    paywallFeatureUnlimited = "Безлимитные сканы",
    paywallFeatureNoWatermarks = "Без рекламы (Premium)",
    paywallFeatureFaster = "Пакетная обработка",
    paywallFeatureCloud = "Приоритетная поддержка",
    paywallMonthlyTitle = "Месячный",
    paywallMonthlySubtitle = "Лучше для знакомства с Premium",
    paywallLifetimeTitle = "Пожизненный (Лучшая цена!)",
    paywallLifetimeSubtitle = "Сэкономьте больше, заплатите один раз",
    paywallChooseLifetime = "Выбрать пожизненный",
    paywallTryMonthly = "Попробовать месячный",
    paywallTerms = "Условия",
    paywallPrivacy = "Конфиденциальность",
    paywallRestore = "Восстановить",
    paywallPriceNote = "Цены могут отличаться в зависимости от страны",
    paywallMonthlyPeriod = "/ месяц",
    paywallLifetimePeriod = "разовая оплата",
    paywallMonthlyFeatureA = "Отмена в любой момент",
    paywallMonthlyFeatureB = "Автопродление",
    paywallLifetimeFeatureA = "Бессрочные обновления",
    paywallLifetimeFeatureB = "Больше не нужно платить",
    showEmptyScans = "Показать пустые",
    hideEmptyScans = "Скрыть пустые",
    photoCreatedAt = "Фото создано",
    syncScreenshotsOnlyTitle = "Синхронизировать только скриншоты",
    syncScreenshotsOnlySubtitle = "Когда включено, синхронизируются только изображения из папок скриншотов",
    clearAllScans = "Очистить все",
    clearAllScansTitle = "Очистить все сканы?",
    clearAllScansMessage = "Все отсканированные записи будут безвозвратно удалены из базы приложения.",
    clearAllScansSuccess = "Все отсканированные записи удалены.",
    // === Onboarding ===
    onboardingTitle1 = "Сканируем вашу галерею",
    onboardingSubtitle1 = "Папка Скриншоты загружается прямо сейчас...",
    onboardingTitle2 = "AI сортирует всё за вас",
    onboardingSubtitle2 = "Чеки, паспорта, договоры — автоматически по папкам",
    skip = "Пропустить",
    next = "Далее",
    done = "Готово",
    // === Scanning Progress ===
    onboardingScanning = "Сканируем вашу галерею...",
    scannedDocuments = "Обработано: %d документов",
    scanningHint = "Это может занять некоторое время...",
    // === Empty State ===
    emptyStateTitle = "Никаких документов?",
    emptyStateSubtitle = "AI сортирует ваши фото и документы автоматически",
    emptyStateTip1 = "Сканируйте чеки, паспорта, договоры",
    emptyStateTip2 = "AI автоматически определяет тип документа",
    emptyStateTip3 = "Всё сортируется по папкам",
    scanFirstDocument = "Сканировать первый документ",
    // === Screenshots Folder Empty ===
    screenshotsFolderEmptyHint = "По умолчанию синхронизируется только папка Скриншоты. Вы можете переключиться на синхронизацию всех фото из галереи.",
    currentlyScreenshotsOnly = "Сейчас: только скриншоты",
    currentlyAllGallery = "Сейчас: вся галерея",
    switchToAllGallery = "Переключить на всю галерею и синхронизировать",
    syncAllGallery = "Синхронизировать всю галерею",
    // === Sync Control ===
    stopSync = "Остановить",
    continueSync = "Продолжить",
    startOver = "Начать заново",
    startOverConfirmTitle = "Начать заново?",
    startOverConfirmMessage = "Это удалит все документы, отсканированные в этой сессии, и начнет заново с начала.",
    startOverConfirm = "Начать заново",
    sortMenu = "Сортировка",
    sortBySyncDate = "По дате синхронизации",
    sortByPhotoDate = "По дате фото",
    russianScanSpeedNotice = "Скорость сканирования на русском языке сейчас ниже. Мы улучшим это в следующем обновлении.",
    // === Sync Metrics ===
    syncMetricsScanned = "Отсканировано: %d",
    syncMetricsElapsedTime = "Время: %s",
    syncMetricsLastSync = "Последняя синхронизация: %s",
    syncMetricsSummaryTitle = "Итоги синхронизации",
    syncMetricsNow = "сейчас",
    syncMetricsMinutesAgo = "%d мин назад",
    syncMetricsHoursAgo = "%d ч назад",
    syncMetricsDaysAgo = "%d дн назад"
)

private val spanishStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Buscar texto y etiquetas",
    syncNow = "Sincronizar ahora",
    syncing = "Sincronizando...",
    grantPermission = "Conceder",
    permissionRequired = "Permite el acceso a los medios para escanear capturas de galería",
    paywallMessage = "Se alcanzo el limite gratuito. Actualiza a Premium para escaneo ilimitado y sin anuncios.",
    buyPremium = "Obtener Premium",
    noTextRecognized = "No se reconoció texto",
    settings = "Configuración",
    language = "Idioma",
    back = "Atrás",
    syncingGallery = "Sincronizando galería...",
    syncComplete = "%s %d, %s %d.",
    freeLimitReached = "%s %d, %s %d. Límite alcanzado.",
    syncedLabel = "Sincronizado",
    skippedLabel = "Omitido",
    imageDetails = "Detalles de imagen",
    share = "Compartir",
    delete = "Eliminar",
    confirmDelete = "¿Eliminar imagen?",
    deleteMessage = "Esta imagen se eliminará permanentemente de la base de datos.",
    cancel = "Cancelar",
    extractedText = "Texto extraído",
    tags = "Etiquetas",
    metadata = "Metadatos",
    status = "Estado",
    scannedAt = "Escaneado en",
    uri = "URI",
    imagePreview = "Vista previa",
    trialUsage = "Prueba: %d/%d escaneos usados",
    trialRemaining = "%d escaneos restantes",
    upgradeCta = "Mejorar",
    premiumLabel = "Premium",
    unlimitedLabel = "Ilimitado",
    screenshotsFolderEmpty = "Tu carpeta de capturas de pantalla esta vacia.",
    paywallTitle = "Mejorar a Premium",
    paywallSubtitle = "Desbloquea escaneo ilimitado y elimina anuncios con Premium",
    paywallFeatureUnlimited = "Escaneos ilimitados",
    paywallFeatureNoWatermarks = "Sin anuncios (Premium)",
    paywallFeatureFaster = "Procesamiento por lotes",
    paywallFeatureCloud = "Soporte prioritario",
    paywallMonthlyTitle = "Mensual",
    paywallMonthlySubtitle = "Ideal para probar premium",
    paywallLifetimeTitle = "De por vida (¡Mejor valor!)",
    paywallLifetimeSubtitle = "Ahorra más, paga una vez para siempre",
    paywallChooseLifetime = "Elegir de por vida",
    paywallTryMonthly = "Probar mensual",
    paywallTerms = "Términos",
    paywallPrivacy = "Privacidad",
    paywallRestore = "Restaurar",
    paywallPriceNote = "Los precios pueden variar según el país",
    paywallMonthlyPeriod = "/ mes",
    paywallLifetimePeriod = "pago único",
    paywallMonthlyFeatureA = "Cancela cuando quieras",
    paywallMonthlyFeatureB = "Renovación automática",
    paywallLifetimeFeatureA = "Actualizaciones ilimitadas",
    paywallLifetimeFeatureB = "Nunca pagues de nuevo",
    showEmptyScans = "Mostrar vacíos",
    hideEmptyScans = "Ocultar vacíos",
    photoCreatedAt = "Foto creada el",
    syncScreenshotsOnlyTitle = "Sincronizar solo capturas",
    syncScreenshotsOnlySubtitle = "Cuando está activado, solo se sincronizan imágenes de carpetas de capturas",
    clearAllScans = "Borrar todo",
    clearAllScansTitle = "Borrar todos los escaneos?",
    clearAllScansMessage = "Esto eliminara permanentemente todos los registros escaneados de la base de datos.",
    clearAllScansSuccess = "Todos los registros escaneados fueron eliminados.",
    // === Onboarding ===
    onboardingTitle1 = "Estamos escaneando tu galería",
    onboardingSubtitle1 = "Tu carpeta de Capturas se está cargando...",
    onboardingTitle2 = "La IA ordena todo por ti",
    onboardingSubtitle2 = "Recibos, pasaportes, contratos — automáticamente organizados",
    skip = "Omitir",
    next = "Siguiente",
    done = "Listo",
    // === Scanning Progress ===
    onboardingScanning = "Escaneando tu galería...",
    scannedDocuments = "Procesados: %d documentos",
    scanningHint = "Esto puede tomar un momento...",
    // === Empty State ===
    emptyStateTitle = "¿Sin documentos aún?",
    emptyStateSubtitle = "La IA ordena automáticamente tus fotos y documentos",
    emptyStateTip1 = "Escanea recibos, pasaportes, contratos",
    emptyStateTip2 = "La IA detecta automáticamente el tipo",
    emptyStateTip3 = "Todo ordenado en carpetas",
    scanFirstDocument = "Escanear primer documento",
    // === Screenshots Folder Empty ===
    screenshotsFolderEmptyHint = "Por defecto, sincronizamos solo la carpeta de Capturas. Puedes cambiar para sincronizar todas las fotos de tu galería.",
    currentlyScreenshotsOnly = "Actualmente: solo capturas",
    currentlyAllGallery = "Actualmente: toda la galería",
    switchToAllGallery = "Cambiar a toda la galería y sincronizar",
    syncAllGallery = "Sincronizar toda la galería",
    // === Sync Control ===
    stopSync = "Detener",
    continueSync = "Continuar",
    startOver = "Empezar de nuevo",
    startOverConfirmTitle = "¿Empezar de nuevo?",
    startOverConfirmMessage = "Esto eliminará todos los documentos escaneados en esta sesión y comenzará desde el principio.",
    startOverConfirm = "Empezar de nuevo",
    sortMenu = "Ordenar",
    sortBySyncDate = "Por fecha de sincronización",
    sortByPhotoDate = "Por fecha de foto",
    russianScanSpeedNotice = "El escaneo en ruso actualmente es más lento. Lo mejoraremos en la próxima actualización.",
    // === Sync Metrics ===
    syncMetricsScanned = "Escaneado: %d",
    syncMetricsElapsedTime = "Tiempo transcurrido: %s",
    syncMetricsLastSync = "Última sincronización: %s",
    syncMetricsSummaryTitle = "Resumen de sincronización",
    syncMetricsNow = "ahora",
    syncMetricsMinutesAgo = "hace %d min",
    syncMetricsHoursAgo = "hace %d h",
    syncMetricsDaysAgo = "hace %d d"
)

private val germanStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "Text und Tags suchen",
    syncNow = "Jetzt synchronisieren",
    syncing = "Synchronisiere...",
    grantPermission = "Gewähren",
    permissionRequired = "Erlaube Medienzugriff zum Scannen von Galerie-Screenshots",
    paywallMessage = "Kostenloses Limit erreicht. Upgrade auf Premium fur unbegrenztes Scannen ohne Werbung.",
    buyPremium = "Premium holen",
    noTextRecognized = "Kein Text erkannt",
    settings = "Einstellungen",
    language = "Sprache",
    back = "Zurück",
    syncingGallery = "Galerie wird synchronisiert...",
    syncComplete = "%s %d, %s %d.",
    freeLimitReached = "%s %d, %s %d. Limit erreicht.",
    syncedLabel = "Synchronisiert",
    skippedLabel = "Übersprungen",
    imageDetails = "Bilddetails",
    share = "Teilen",
    delete = "Löschen",
    confirmDelete = "Bild löschen?",
    deleteMessage = "Dieses Bild wird dauerhaft aus der Datenbank gelöscht.",
    cancel = "Abbrechen",
    extractedText = "Extrahierter Text",
    tags = "Tags",
    metadata = "Metadaten",
    status = "Status",
    scannedAt = "Gescannt am",
    uri = "URI",
    imagePreview = "Bildvorschau",
    trialUsage = "Testphase: %d/%d Scans genutzt",
    trialRemaining = "%d Scans verbleibend",
    upgradeCta = "Upgrade",
    premiumLabel = "Premium",
    unlimitedLabel = "Unbegrenzt",
    screenshotsFolderEmpty = "Dein Screenshot-Ordner ist leer.",
    paywallTitle = "Auf Premium upgraden",
    paywallSubtitle = "Schalte unbegrenztes Scannen frei und entferne Werbung mit Premium",
    paywallFeatureUnlimited = "Unbegrenzte Scans",
    paywallFeatureNoWatermarks = "Keine Werbung (Premium)",
    paywallFeatureFaster = "Stapelverarbeitung",
    paywallFeatureCloud = "Priorisierter Support",
    paywallMonthlyTitle = "Monatlich",
    paywallMonthlySubtitle = "Ideal zum Ausprobieren von Premium",
    paywallLifetimeTitle = "Lebenslang (Bestes Angebot!)",
    paywallLifetimeSubtitle = "Mehr sparen, einmal zahlen",
    paywallChooseLifetime = "Lebenslang wählen",
    paywallTryMonthly = "Monatlich testen",
    paywallTerms = "AGB",
    paywallPrivacy = "Datenschutz",
    paywallRestore = "Wiederherstellen",
    paywallPriceNote = "Preise können je nach Land variieren",
    paywallMonthlyPeriod = "/ Monat",
    paywallLifetimePeriod = "einmalig",
    paywallMonthlyFeatureA = "Jederzeit kündbar",
    paywallMonthlyFeatureB = "Automatische Verlängerung",
    paywallLifetimeFeatureA = "Unbegrenzte Updates",
    paywallLifetimeFeatureB = "Nie wieder zahlen",
    showEmptyScans = "Leere anzeigen",
    hideEmptyScans = "Leere ausblenden",
    photoCreatedAt = "Foto erstellt am",
    syncScreenshotsOnlyTitle = "Nur Screenshots synchronisieren",
    syncScreenshotsOnlySubtitle = "Wenn aktiviert, werden nur Bilder aus Screenshot-Ordnern synchronisiert",
    clearAllScans = "Alles loschen",
    clearAllScansTitle = "Alle Scans loschen?",
    clearAllScansMessage = "Dadurch werden alle gescannten Eintrage dauerhaft aus der App-Datenbank entfernt.",
    clearAllScansSuccess = "Alle gescannten Eintrage wurden entfernt.",
    // === Onboarding ===
    onboardingTitle1 = "Wir scannen Ihre Galerie",
    onboardingSubtitle1 = "Ihr Screenshot-Ordner wird gerade geladen...",
    onboardingTitle2 = "KI sortiert alles für Sie",
    onboardingSubtitle2 = "Quittungen, Pässe, Verträge — automatisch organisiert",
    skip = "Überspringen",
    next = "Weiter",
    done = "Fertig",
    // === Scanning Progress ===
    onboardingScanning = "Ihre Galerie wird gescannt...",
    scannedDocuments = "Verarbeitet: %d Dokumente",
    scanningHint = "Dies kann einen Moment dauern...",
    // === Empty State ===
    emptyStateTitle = "Noch keine Dokumente?",
    emptyStateSubtitle = "KI sortiert Ihre Fotos und Dokumente automatisch",
    emptyStateTip1 = "Scannen Sie Quittungen, Pässe, Verträge",
    emptyStateTip2 = "KI erkennt den Typ automatisch",
    emptyStateTip3 = "Alles in Ordner sortiert",
    scanFirstDocument = "Erstes Dokument scannen",
    // === Screenshots Folder Empty ===
    screenshotsFolderEmptyHint = "Standardmäßig synchronisieren wir nur den Screenshot-Ordner. Sie können zur Synchronisierung aller Fotos aus Ihrer Galerie wechseln.",
    currentlyScreenshotsOnly = "Aktuell: nur Screenshots",
    currentlyAllGallery = "Aktuell: gesamte Galerie",
    switchToAllGallery = "Zu gesamter Galerie wechseln & synchronisieren",
    syncAllGallery = "Gesamte Galerie synchronisieren",
    // === Sync Control ===
    stopSync = "Stoppen",
    continueSync = "Fortsetzen",
    startOver = "Neu starten",
    startOverConfirmTitle = "Neu starten?",
    startOverConfirmMessage = "Dadurch werden alle in dieser Sitzung gescannten Dokumente gelöscht und von vorne begonnen.",
    startOverConfirm = "Neu starten",
    sortMenu = "Sortieren",
    sortBySyncDate = "Nach Synchronisierungsdatum",
    sortByPhotoDate = "Nach Fotodatum",
    russianScanSpeedNotice = "Das Scannen auf Russisch ist derzeit langsamer. Wir verbessern das im nächsten Update.",
    // === Sync Metrics ===
    syncMetricsScanned = "Gescannt: %d",
    syncMetricsElapsedTime = "Verstrichene Zeit: %s",
    syncMetricsLastSync = "Letzte Synchronisierung: %s",
    syncMetricsSummaryTitle = "Synchronisierungszusammenfassung",
    syncMetricsNow = "jetzt",
    syncMetricsMinutesAgo = "vor %d Min",
    syncMetricsHoursAgo = "vor %d Std",
    syncMetricsDaysAgo = "vor %d Tg"
)

private val chineseStrings = StringResources(
    appName = "SmartScan AI",
    searchHint = "搜索文本和标签",
    syncNow = "立即同步",
    syncing = "同步中...",
    grantPermission = "授权",
    permissionRequired = "允许访问媒体以扫描图库截图",
    paywallMessage = "已达到免费限制。升级到 Premium 享受无限扫描和无广告。",
    buyPremium = "获取 Premium",
    noTextRecognized = "未识别到文本",
    settings = "设置",
    language = "语言",
    back = "返回",
    syncingGallery = "正在同步图库...",
    syncComplete = "%s %d，%s %d。",
    freeLimitReached = "%s %d，%s %d。已达到免费限制。",
    syncedLabel = "已同步",
    skippedLabel = "已跳过",
    imageDetails = "图片详情",
    share = "分享",
    delete = "删除",
    confirmDelete = "删除图片？",
    deleteMessage = "该图片将从本地数据库中永久删除。",
    cancel = "取消",
    extractedText = "识别文本",
    tags = "标签",
    metadata = "元数据",
    status = "状态",
    scannedAt = "扫描时间",
    uri = "URI",
    imagePreview = "图片预览",
    trialUsage = "试用期：已使用 %d/%d 次扫描",
    trialRemaining = "剩余 %d 次扫描",
    upgradeCta = "升级",
    premiumLabel = "Premium",
    unlimitedLabel = "无限",
    screenshotsFolderEmpty = "你的截图文件夹是空的。",
    paywallTitle = "升级到 Premium",
    paywallSubtitle = "升级 Premium，解锁无限扫描并关闭广告",
    paywallFeatureUnlimited = "无限扫描",
    paywallFeatureNoWatermarks = "无广告 (Premium)",
    paywallFeatureFaster = "批量处理",
    paywallFeatureCloud = "优先支持",
    paywallMonthlyTitle = "月付",
    paywallMonthlySubtitle = "适合先体验 Premium",
    paywallLifetimeTitle = "终身版（最佳价值！）",
    paywallLifetimeSubtitle = "一次付费，永久使用",
    paywallChooseLifetime = "选择终身版",
    paywallTryMonthly = "试用月付",
    paywallTerms = "条款",
    paywallPrivacy = "隐私",
    paywallRestore = "恢复购买",
    paywallPriceNote = "价格可能因地区而异",
    paywallMonthlyPeriod = "/ 月",
    paywallLifetimePeriod = "一次性",
    paywallMonthlyFeatureA = "可随时取消",
    paywallMonthlyFeatureB = "自动续订",
    paywallLifetimeFeatureA = "无限更新",
    paywallLifetimeFeatureB = "无需再次付费",
    showEmptyScans = "显示空白",
    hideEmptyScans = "隐藏空白",
    photoCreatedAt = "照片创建时间",
    syncScreenshotsOnlyTitle = "仅同步截图",
    syncScreenshotsOnlySubtitle = "开启后，仅同步截图文件夹中的图片",
    clearAllScans = "清空全部",
    clearAllScansTitle = "清空所有扫描记录？",
    clearAllScansMessage = "这将删除本次会话中扫描的所有文档，并从头开始。",
    clearAllScansSuccess = "所有扫描记录已删除。",
    // === Onboarding ===
    onboardingTitle1 = "正在扫描您的图库",
    onboardingSubtitle1 = "您的屏幕截图文件夹正在加载...",
    onboardingTitle2 = "AI 为您自动分类",
    onboardingSubtitle2 = "发票、护照、合同 — 自动分类",
    skip = "跳过",
    next = "下一步",
    done = "完成",
    // === Scanning Progress ===
    onboardingScanning = "正在扫描您的图库...",
    scannedDocuments = "已处理：%d 个文档",
    scanningHint = "这可能需要一些时间...",
    // === Empty State ===
    emptyStateTitle = "还没有文档？",
    emptyStateSubtitle = "AI 自动分类您的照片和文档",
    emptyStateTip1 = "扫描发票、护照、合同",
    emptyStateTip2 = "AI 自动检测文档类型",
    emptyStateTip3 = "所有文件按文件夹分类",
    scanFirstDocument = "扫描首个文档",
    // === Screenshots Folder Empty ===
    screenshotsFolderEmptyHint = "默认情况下，我们仅同步屏幕截图文件夹。您可以切换为同步图库中的所有照片。",
    currentlyScreenshotsOnly = "当前：仅截图",
    currentlyAllGallery = "当前：全部图库",
    switchToAllGallery = "切换到全部图库并同步",
    syncAllGallery = "同步全部图库",
    // === Sync Control ===
    stopSync = "停止",
    continueSync = "继续",
    startOver = "重新开始",
    startOverConfirmTitle = "重新开始？",
    startOverConfirmMessage = "这将删除本次会话中扫描的所有文档，并从头开始。",
    startOverConfirm = "重新开始",
    sortMenu = "排序",
    sortBySyncDate = "按同步日期",
    sortByPhotoDate = "按照片日期",
    russianScanSpeedNotice = "俄语扫描当前速度较慢。我们将在下次更新中改进。",
    // === Sync Metrics ===
    syncMetricsScanned = "已扫描: %d",
    syncMetricsElapsedTime = "耗时: %s",
    syncMetricsLastSync = "上次同步: %s",
    syncMetricsSummaryTitle = "同步摘要",
    syncMetricsNow = "刚刚",
    syncMetricsMinutesAgo = "%d分钟前",
    syncMetricsHoursAgo = "%d小时前",
    syncMetricsDaysAgo = "%d天前"
)
